name: Auto Pull Request

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Install hub
      run: |
        sudo apt-get update
        sudo apt-get install -y hub


    - name: Create Pull Request to dev
      run: |
        git checkout -b auto-pr-dev
        git push --set-upstream origin auto-pr-dev
        hub pull-request -b dev -h auto-pr-dev -m "Automated Pull Request to dev" || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge_to_main:
    needs: create_pull_request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Merge Pull Request to main
      run: |
        git checkout main
        git pull origin main
        git merge --no-ff auto-pr-dev
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
