name: Auto Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Create Pull Request to dev
      run: |
        git push origin HEAD:refs/heads/dev -f
        hub pull-request -b dev -h "${{ github.actor }}:dev" -m "Automated Pull Request to dev" || true
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  merge_to_main:
    needs: create_pull_request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Merge Pull Request to main
      run: |
        git fetch origin dev:dev
        git checkout main
        git merge --no-ff dev
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
