name: Auto Pull Request

on:
  push:
    branches:
      - '*'
      - '!main'  # Update this line if your default branch is 'master'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Install hub
      run: |
        sudo apt-get update
        sudo apt-get install -y hub

    - name: Extract commit message
      id: extract_commit_message
      run: |
        COMMIT_MESSAGE=$(git log --format=%B -n 1 "${{ github.sha }}")
        echo "Commit Message: $COMMIT_MESSAGE"
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Create Pull Request to dev
      run: |
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref != 'refs/heads/dev' }}" ]; then
          hub pull-request -b dev -h "${{ github.ref }}" -m "$COMMIT_MESSAGE" || true
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create Pull Request to main from dev
      run: |
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref == 'refs/heads/dev' }}" ]; then
          git checkout -b auto-pr-main
          git push --set-upstream origin auto-pr-main
          hub pull-request -b main -h auto-pr-main -m "Automated Pull Request to main" || true
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
